# Generated by Django 4.2.7 on 2026-02-09 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_id", models.CharField(max_length=100, unique=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("EDGE", "Edge Computing Node"),
                            ("CORE", "Core Network Node"),
                            ("IOT", "IoT Device"),
                            ("USER", "User Equipment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("hardware_capability", models.IntegerField(default=1)),
                ("network_bandwidth", models.FloatField(default=100.0)),
                ("reputation_score", models.FloatField(default=5.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shard_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("URLLC", "Ultra-Reliable Low Latency"),
                            ("EMBB", "Enhanced Mobile Broadband"),
                            ("MIOT", "Massive IoT"),
                            ("MEC", "Multi-access Edge Computing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("minimum_reputation", models.FloatField(default=3.0)),
                ("minimum_capability", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=64, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DATA_SHARE", "Data Sharing"),
                            ("RESOURCE_ALLOC", "Resource Allocation"),
                            ("SERVICE_REQ", "Service Request"),
                            ("CONSENSUS", "Consensus Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_size", models.IntegerField(default=0)),
                ("payload_hash", models.CharField(max_length=64)),
                ("offchain_storage_ref", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("consensus_rounds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to="core.node",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transactions",
                        to="core.node",
                    ),
                ),
                (
                    "shard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.shard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("ON_CHAIN", "On-chain"), ("OFF_CHAIN", "Off-chain")],
                        max_length=20,
                    ),
                ),
                ("data_hash", models.CharField(max_length=64)),
                ("storage_location", models.CharField(max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("size_bytes", models.IntegerField(default=0)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_records",
                        to="core.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReputationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_score", models.FloatField()),
                ("new_score", models.FloatField()),
                ("reason", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_history",
                        to="core.node",
                    ),
                ),
                (
                    "shard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.shard",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ShardMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEADER", "Shard Leader"),
                            ("VALIDATOR", "Validator"),
                            ("OBSERVER", "Observer"),
                        ],
                        default="VALIDATOR",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("reputation_in_shard", models.FloatField(default=5.0)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shard_memberships",
                        to="core.node",
                    ),
                ),
                (
                    "shard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.shard",
                    ),
                ),
            ],
            options={
                "unique_together": {("node", "shard")},
            },
        ),
        migrations.CreateModel(
            name="ConsensusRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRE_PREPARE", "Pre-prepare"),
                            ("PREPARE", "Prepare"),
                            ("COMMIT", "Commit"),
                            ("DECIDED", "Decided"),
                        ],
                        default="PRE_PREPARE",
                        max_length=20,
                    ),
                ),
                ("load_factor", models.FloatField(default=0.5)),
                ("batch_size", models.IntegerField(default=10)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.node",
                    ),
                ),
                (
                    "shard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_rounds",
                        to="core.shard",
                    ),
                ),
            ],
            options={
                "unique_together": {("shard", "round_number")},
            },
        ),
    ]
