# Generated by Django 4.2.7 on 2026-02-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consensusround",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="consensusround",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.node",
            ),
        ),
        migrations.AlterField(
            model_name="consensusround",
            name="round_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="consensusround",
            name="shard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consensus_rounds",
                to="core.shard",
            ),
        ),
    ]
