# Generated by Django 4.2.7 on 2026-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_consensusround_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='offchain_storage_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
